version: '3'
services:
  web:
    image: payara/micro:5.183
    ports:
      - 8080:8080
    volumes:
      - "./target:/opt/payara/deployments"
  prometheus:
    image: prom/prometheus:v2.4.3
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:5.3.1
    ports:
      - 3000:3000